### ISSUE TITLE
maven-java11 builder picking up old doclet for javadoc

### ISSUE THREAD

**Issue by ryandawsonuk** [jenkins-x/jenkins-x-builders#236]
We discussed this with  @hekonsek who created a standard spring initializr project for java11 (https://github.com/hekonsek/ddewdfewr4554t54t54t) and with that project we can reproduce the issue using

 ```
docker run -it jenkinsxio/builder-maven-java11:0.1.207 bash
git clone https://github.com/hekonsek/ddewdfewr4554t54t54t
cd ddewdfewr4554t54t54t
mvn javadoc:javadoc
```

And I see:
![image](https://user-images.githubusercontent.com/22754674/51674700-50714980-1fc9-11e9-8905-3bf78977c558.png)

The original issue is https://github.com/Activiti/Activiti/issues/2384

**Comment by hekonsek** [comment]
OK. I've nailed it :) Doclet version is resolved from `javadoc` command which I forget to link to PATH in the initial version of the builder. Fix is here - https://github.com/jenkins-x/jenkins-x-builders/pull/239 .

**Comment by hekonsek** [comment]
@ryandawsonuk Can you give the new image a try and let us know if it does the job? :) Thanks!

**Comment by garethjevans** [comment]
@hekonsek @ryandawsonuk are you happy with the fix? I'd like to get this closed if possible

**Comment by ryandawsonuk** [comment]
Looks good. Have rechecked the above steps with new version using `docker run -it jenkinsxio/builder-maven-java11:0.1.207 bash` and doclet shows 11.0.2 now.

**Comment by garethjevans** [comment]
Thanks, will close the ticket
