### ISSUE TITLE
builder for PHP?

### ISSUE THREAD

**Issue by pzheng64** [jenkins-x/jenkins-x-builders#484]
Is there jx builder for PHP 5 or PHP 7? I wanted to test for `jx import` of Laravel project, but could not get it working.

**Comment by Larzack** [comment]
+1

**Comment by dennisnewel** [comment]
raised a PR with a builder for each. I'm not a PHP user though, so not sure if other things should be included by default. @pzheng64 and @Larzack please review

**Comment by dennisnewel** [comment]
waiting for two more PRs to go through: 
- https://github.com/jenkins-x/jenkins-x-platform/pull/6076
- https://github.com/jenkins-x/jenkins-x-versions/pull/494
