### ISSUE TITLE
builder-nodejs8x has node 10 instead of 8

### ISSUE THREAD

**Issue by gazal-k** [jenkins-x/jenkins-x-builders#533]
**Steps**
docker pull gcr.io/jenkinsxio/builder-nodejs8x:0.1.543
docker run -it gcr.io/jenkinsxio/builder-nodejs8x:0.1.543 bash
node -v
npm -v

**Expected**
v8.x (nodejs version)
5.x (npm version)

**Actual**
v10.16.0
6.9.0

**Comment by dennisnewel** [comment]
this seems to have been fixed at some point in time.
Latest (0.1.722) reports

v8.16.1
6.4.1

**Comment by gazal-k** [comment]
Thanks @dennisnewel
